apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${REDIS_DEPLOYMENT_NAME}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-lookup-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: redis-lookup-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: redis-lookup-server
    spec:
      containers:
        - name: lookup-server
          image: ${REDIS_IMAGE}:${REDIS_TAG}
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
          ports:
            - name: redis-port
              containerPort: ${REDIS_TARGET_PORT}
              protocol: TCP
          resources:
            limits:
              cpu: "4"
              memory: 10G
            requests:
              cpu: "4"
              memory: 8G
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
