version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true
    
# Settings related to issues
issues:
  # Report issues on new code only (since we're brining in from upstream)
  new: true
  # Which dirs to exclude: issues from them won't be reported
  exclude-dirs:
    - bin
  # Files to exclude from linting
  exclude-files:
    - pkg/epp/server/runserver_test.go
    
linters:
  disable-all: true
  disable:
    - goanalysis_metalinter
  enable:
    - copyloopvar
    - dupword
    - durationcheck
    - fatcontext
    - ginkgolinter
    - gocritic
    - govet        
    - loggercheck
    - misspell
    - perfsprint
    - revive
    - unconvert
    - makezero
    - errcheck
    - goconst
    - ineffassign
    - nakedret
    - prealloc
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings